version: "3.8"

services:
  app:
    image: openjdk:17-jdk
    container_name: spring-app
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "stormpaws-0.0.1-SNAPSHOT.jar"]
    expose:
      - "8080"
    networks:
      - app-net
    restart: unless-stopped

  caddy:
    image: jaredlander/caddy-dns:duckdns-latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
