version: "3.8"

services:
  app:
    image: openjdk:17-jdk
    container_name: spring-app
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "stormpaws-0.0.1-SNAPSHOT.jar"]
    expose:
      - "8080"
    networks:
      - app-net
    restart: "no"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-net
    restart: "no"

networks:
  app-net:
    driver: bridge
