POST {{stormpaw-host}}/battles/pvp/computer/random
Content-Type: application/json

{
  "attackerDeckId": "78ac72fe-a6e7-4769-87cd-7ef3b562ccac",
  "attackerUserId": "test-user-id",
  "weatherLogId": "aacbd4e0-08a6-4267-811e-590340bd353b"
}