POST {{stormpaw-host}}/battles/pvp
Content-Type: application/json

{
  "attackerDeckId": "77b64d8c-1608-45cb-92e6-cc41a3fd2919",
  "attackerUserId": "test-user-id",
  "defenderDeckId": "18dd1b82-5a38-4bcd-a174-15fc7f63fa08",
  "defenderUserId": "400e36e4-741d-4e3b-b32a-7c90400d2c30",
  "weatherLogId": "7ecb2b73-781c-4666-a2c3-1382209a0d4f"
}