POST {{stormpaw-host}}/user/me/decks
Content-Type: application/json
Authorization: Bearer {{stormpaw-jwt}}

{
  "name": "my_deck2",
  "cards": [
    {
      "cardId": "a1111111-1111-1111-1111-111111111111",
      "quantity": 5,
      "pos": 1
    },
    {
      "cardId": "b2222222-2222-2222-2222-222222222222",
      "quantity": 5,
      "pos": 2
    },
    {
      "cardId": "c3333333-3333-3333-3333-333333333333",
      "quantity": 5,
      "pos": 3
    },
    {
      "cardId": "d4444444-4444-4444-4444-444444444444",
      "quantity": 5,
      "pos": 4
    },
    {
      "cardId": "e5555555-5555-5555-5555-555555555555",
      "quantity": 5,
      "pos": 5
    }
  ]
}
